adadis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("store.urls")),
    path('usuarios/', include("users.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.contrib import admin
from django.urls import path
from . views import Index, Details, welcome_page

app_name = "store"

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('welcome', welcome_page, name='welcome'),
    path('details/<int:pk>', Details.as_view(), name='details'),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.view_login, name="login"),
]

store/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    titulo = models.CharField(max_length=70)
    descripcion = models.TextField()
    precio = models.IntegerField()
    imagen = models.ImageField(upload_to='store/img', default='store/img/default_image.jpg', null=True)

    def __str__(self):
        return self.titulo

users/models.py
from django.db import models

# Create your models here.

store/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.forms import AuthenticationForm
from .models import Product


# Create your views here.
class Index(generic.ListView):
    model = Product
    template_name = 'store/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form_login"] = AuthenticationForm
        return context


class Details(generic.DetailView):
    model = Product
    template_name = 'store/product_details.html'


def welcome_page(request):
    return render(request, 'store/welcome.html')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login

# Create your views here.
def view_login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('store:welcome')

store/templates/store/index.html
{% extends 'store/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}


<!--  Productos  -->
<div class="container mt-5">
    <div class="row justify-content-center align-items-stretch">
        {% for producto in object_list %}
        <div class="card mb-4 col-md-3 mx-3 text-product card-products">
            <a href="{% url 'store:details' pk=producto.id %} ">
                {% if producto.imagen %}
                <div class=" d-flex flex-column justify-content-between product-card">
                    <img src="{{ producto.imagen.url }}" alt="{{ producto.titulo }}" class="card-img-top" />
                    <span class="product-price-badge">{{ producto.precio|intcomma }} CLP</span>
                </div>

                {% endif %}
                <div class="card-body d-flex flex-column justify-content-between">
                    <h5 class="card-title mb-0">
                        {{ producto.titulo }}
                    </h5>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

store/templates/store/product_details.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}

{% block title %}<title>{{ object.titulo }}</title>{% endblock %} 
<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
      <div class="col-md-4">
        <div class="card">
          <img src="{{ object.imagen.url }}" class="card-img-top imgCardProducto" alt="Fissure in Sandstone" />
        </div>
      </div>
      <div class="col-md-8">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{ object.titulo }}</h5>
            <p class="card-text product-description">{{ object.descripcion }}</p>
            <p class="product-price">Precio: ${{ object.precio }}</p>
  
            <div class="row align-items-center">
              <div class="col-md-4 mb-3">
                <div class="input-group">
                  <span class="input-group-text">Cantidad:</span>
                  <button class="btn btn-outline-secondary" type="button" id="decrement-btn">-</button>
                  <input type="text" class="form-control" id="cantidad" value="1" readonly>
                  <button class="btn btn-outline-secondary " type="button" id="increment-btn">+</button>
                </div>
              </div>
              <div class="col-md-8">
                <a href="#!" class="btn btn-primary me-3 font-button">Añadir al Carrito</a>
                <a href="#!" class="btn btn-primary font-button">Comprar</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <script>
    document.addEventListener("DOMContentLoaded", function () {
      const incrementBtn = document.getElementById("increment-btn");
      const decrementBtn = document.getElementById("decrement-btn");
      const cantidadInput = document.getElementById("cantidad");
  
      incrementBtn.addEventListener("click", function () {
        let cantidad = parseInt(cantidadInput.value);
        cantidadInput.value = cantidad + 1;
      });
  
      decrementBtn.addEventListener("click", function () {
        let cantidad = parseInt(cantidadInput.value);
        if (cantidad > 1) {
          cantidadInput.value = cantidad - 1;
        }
      });
    });
  </script>


{% endblock %}

store/templates/store/welcome.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}

<div class="slider-container">
    <div class="slider">
        <div class="slide">
            <img src="{% static '/store/img/slider1.jpg' %}" alt="">
            <div class="slide-content">
                <h1>BIENVENIDOS A LA TIENDA NO OFICIAL</h1>
            </div>
        </div>
        <div class="slide">
            <img src="{% static '/store/img/slider2.jpg' %}" alt="">
            <div class="slide-content">
                <h1>BIENVENIDOS</h1>
            </div>
        </div>
        <div class="slide"><img src="{% static '/store/img/slider3.jpg' %}" alt=""></div>
       
    </div>
</div>

<script>
    const slider = document.querySelector('.slider');
    let slideIndex = 0;

    function showSlide(index) {
        slider.style.transform = `translateX(-${index * 100}%)`;
    }

    function nextSlide() {
        slideIndex = (slideIndex + 1) % slider.childElementCount;
        showSlide(slideIndex);
    }

    setInterval(nextSlide, 8000);
    showSlide(slideIndex);

</script>

{% endblock %}